<?php
namespace Modules\Itinerary\ItinerayControllers;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Modules\AdminController;


class ItineraryController extends AdminController
{

    public function __construct()
    {
        $this->setActiveMenu(route('itinerary.admin.index'));
    }
    public function callAction($method, $parameters)
    {
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

public function index(Request $request)
{
    $this->checkPermission('itinerary_view');

  
    $data = [
        'rows'               => $query->with(['author'])->paginate(20),
        'breadcrumbs'        => [
            [
                'name'  => __('Itinerary'),
                'class' => 'active'
            ],
        ],
        'page_title'=>__("Itinerary"),
    ];
    return view('Itinerary::admin.index', $data);
}

}